
name: cluster

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  localhost:
    runs-on: ubuntu-22.04
    steps:
      - id: env-setup
        run: |
          echo "env_token=production" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.env-setup.outputs.env_token }}"
      - name: Check for outdated packages
        id: vars
        run: |
           OUTDATED=true|| true
           echo "OUTDATED={OUTDATED}" >> $GITHUB_OUTPUT
      - name: Upgrade
        run: echo ${{ steps.vars.outputs.cluster_id_computed }}
      - name: Create cluster ID
        run: |
          export suffix=artefact-test-dummy
          #export cluster_id_computed=(ci-${{github.event.number}}-$suffix)
          export cluster_id_computed=ci-123-dummy
          echo "cluster_id_computed=baz" >> $GITHUB_OUTPUT
        shell: bash
      - name: Check cluster ID
        id: test-artefact
        run: echo ${{ steps.test-artefact.outputs.cluster_id_computed }}
        shell: bash
