
name: merge

on:
  pull_request:
    types: [closed]
    branches: 
      - main
  workflow_run:
    workflows: ["pull-request"]
    types:
      - completed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v3
