
name: merge

on:
  pull_request:
    types: [closed]
    branches: 
      - main

jobs:
  build:
    uses: .github/workflows/.pull-request.yaml
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    needs:
     [ build ]
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v3
