
name: notifications

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  notifications:
    runs-on: ubuntu-22.04
    if: always()
    steps:
      - name: setup
        run: |
          echo setup
      - name: notify
        run: |
          false
      - name: post notify
        if: always()
        run: |
          echo done
      - name: foobar
        run: |
          set +e
          set +o pipefail

          function wrap_command() {
            hjhj
            return $?
          }

          wrap_command
          echo $?
          exit 0
