
name: notifications

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  notifications:
    runs-on: ubuntu-22.04
    if: always()
    steps:
      - name: setup
        run: |
          echo setup
      - name: notify
        if: always()
        run: |
          false
      - name: post notify
        run: |
          echo done
