
name: cluster

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  localhost:
    runs-on: ubuntu-22.04
    steps:
      - name: Build name
        run: |
          dest="production"
          if [ ${{ github.event_name }} == 'pull_request' ]; then dest="staging" ; fi
          echo dest="$dest" >> $GITHUB_OUTPUT
      - name: Check cluster ID
        id: test-artefact
        run: echo ${{ steps.test-artefact.outputs.dest }}
        shell: bash
