
name: services

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  localhost:
    runs-on: ubuntu-22.04
    services:
      elasticmq:
        image: softwaremill/elasticmq-native
    steps:
      - name: Install aws-cli
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: 2
      - run: aws --version
        shell: bash
