
name: services

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  localhost:
    runs-on: ubuntu-22.04
    services:
      elasticmq:
        image: softwaremill/elasticmq-native
    steps:
      - name: Install aws-cli
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: 2
      - name: Check version
        run: aws --version
        shell: bash
      - name: Creat SQS queue
        run: |
          aws sqs create-queue --queue-name sreeQ --endpoint http://elasticmq:9324 --region eu-west-1
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_DEFAULT_REGION: 'eu-west-1'
      
