
name: services

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  localhost:
    runs-on: ubuntu-22.04
    container:
      image: softwaremill/elasticmq-native
      volumes:
          - ${{ github.workspace }}/config:/opt
    steps:
      - name: Check cosmos config file
        run: |
          ls -al /opt
          cat  /opt/elasticmq.conf
