
name: services

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  localhost:
    runs-on: ubuntu-22.04
    services:
      elasticmq:
        image: softwaremill/elasticmq-native
        volumes:
          - docs2:/opt
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: test service
        run: |
          curl -vv localhost:12111
