
name: services

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  localhost:
    runs-on: ubuntu-22.04
    services:
      stripe:
        image: softwaremill/elasticmq-native
        volumes:
          - ${{ github.workspace }}/mkdocs.yml:/opt/docker/conf/elasticmq.conf
        ports:
          - 12111:12111
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: test service
        run: |
          curl -vv localhost:12111
