name: docs-workflow

on:
  push:
  
permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "event name is:" ${{ github.event_name }} 
      - run: echo "event type is:" ${{ github.event.action }}
      - run: echo "github branch is:" ${{ github.branch }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo  "$GITHUB_CONTEXT"
      
  build:
    if: github.event.pull_request.opened == 'true'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: install dependencies
        run: pip install -r requirements.txt

      - name: build docs
        run: mkdocs build

  test:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
    runs-on: ubuntu-22.04
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          
  deploy:
    if: github.event.pull_request.merged == 'true' && github.branch == 'main'
    runs-on: ubuntu-22.04
    needs: [ build, test ]
    steps:
      - uses: actions/checkout@v3
