
name: docs

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: prepare environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.10
      - name: dependencies
        run: pip install -r requirements.txt
      - name: lint
        uses: pre-commit/action@v3.0.0
      - name: unit tests
        run: echo "make build-docs"

  deploy:
    if: github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-22.04
    needs:
      - test
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: prepare environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.10
      - name: dependencies
        run: pip install -r requirements.txt
      - name: build
        run: mkdocs build
      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'site/'
      - name: deploy to gitHub pages
        id: deployment
        uses: actions/deploy-pages@v1
