
name: docs

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: prepare environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.10
      - name: dependencies
        run: pip install -r requirements.txt
      - name: lint
        uses: pre-commit/action@v3.0.0
        continue-on-error: true
      - name: unit tests
        run: mkdocs build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: site/
          
  deploy-test:
    runs-on: ubuntu-22.04
    steps:
      - name: preveiw
        run: echo "preview"
      - name: upload
        if: github.event_name == 'push' && github.ref_name == 'main'
        run: echo "upload"

  deploy:
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-22.04
    needs:
      - test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: site/
      - name: preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site/
      - name: upload pages artifact
        if: github.event_name == 'push' && github.ref_name == 'main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'site/'
      - name: deploy to gitHub pages
        if: github.event_name == 'push' && github.ref_name == 'main'
        id: deployment
        uses: actions/deploy-pages@v1
